# k8s/db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: student-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=       # base64 encoded "postgres"
  DB_PASSWORD: cG9zdGdyZXM=   # base64 encoded "postgres"
  DB_NAME: c3R1ZGVudGRi       # base64 encoded "studentdb"
